{% set name = "PANDORA" %}
{% set version = "2.0.0alpha1" %}
{% set build_number = "0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
 git_rev:
 git_url: git@github.com:X-lab-3D/PANDORA.git
 git_tag: update_external_database

build:
 number: {{ build_number }}
 script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"

requirements:
  build:
    - python>=3.7
    - setuptools
    - pip
  host:
    - python>=3.7

  run:
    - biopython
    - modeller
    - muscle=5.1
    - blast=2.10
    - numpy
    - numpy-base
    - pip
    - python>=3.7
    - setuptools
    - joblib
    - pandas
    - python-dateutil

about:
  home: https://github.com/X-lab-3D/PANDORA/blob/master/README.md
  license: Apache License 2.0
  summary: "PANDORA is anchor restrained modelling pipeline for generating peptide-MHC structures."
  doc_ulr: https://csb-pandora.readthedocs.io/en/latest/?badge=latest

outputs:
    name: setup_database
    script: conda_setup.py
    script_interpreter: python