#! /bin/tcsh -f

# This the main NetMHCIIpan 4.0 script. It only acts as the frontend to the
# software proper, a compiled binary.
# 
# VERSION:	April 2020
# 

###############################################################################
#               GENERAL SETTINGS: CUSTOMIZE TO YOUR SITE
###############################################################################

# full path to the NetMHCIIpan 4.0 directory (mandatory)
setenv	NMHOME	/Users/derek/Dropbox/Master_Bioinformatics/Internship/PANDORA/netMHCIIpan-4.0
setenv	TMPDIR	/Users/derek/Dropbox/Master_Bioinformatics/Internship/PANDORA/netMHCIIpan-4.0/tmp
# determine where to store temporary files (must be writable to all users)

if ( ${?TMPDIR} == 0 ) then
	setenv  TMPDIR  /tmp/
endif

# determine platform (do not change this unless you don't have 'uname'!)
setenv	UNIX	`uname -s`
setenv	AR	`uname -m`

###############################################################################
#               NOTHING SHOULD NEED CHANGING BELOW THIS LINE!
###############################################################################

# other settings
set PLATFORM = `echo $UNIX $AR | awk '{print $1"_"$2}'`
setenv NETMHCIIpan $NMHOME
setenv NetMHCIIpanPLAT $NMHOME/$PLATFORM
setenv NetMHCIIpanWWWPATH /services/NetMHCIIpan-4.0/tmp
setenv NetMHCIIpanWWWDIR /usr/opt/www/pub/CBS/services/NetMHCIIpan-4.0/tmp


# main ========================================================================
if ( -x $NETMHCIIpan/NetMHCIIpan-4.0.pl ) then
   $NETMHCIIpan/NetMHCIIpan-4.0.pl $*
else
   echo $NETMHCIIpan/NetMHCIIpan-4.0.pl not found
endif

# end of script ===============================================================
